services:
  db:
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/code/db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 5s
      retries: 5
    
  back:
    build:
      context: ./back/app
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./back/app:/code/app
    ports:
      - "80:80"
    depends_on:
      - db
    #command: tail -f /dev/null

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./front:/code/front
    depends_on:
      - back