services:
  db:
    build: db
    environment:
      - POSTGRES_PASSWORD={$DB_PASS}
      - POSTGRES_USER={$DB_USER}
      - POSTGRES_DB={$DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    
  back:
    build: app
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./app:/code/app
    ports:
      - "80:80"
    depends_on:
      - db

  front:
    build: front
    ports:
      - "80:7777"
    volumes:
      - ./front:/code/front
    depends_on:
      - back